Step 1 — Import ML libraries

In [3]:
import pandas as pd
import joblib

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report
)

Step 2 — Load the data again

In [4]:
train_df = pd.read_csv("../data/train.csv")
test_df = pd.read_csv("../data/test.csv")

X_train = train_df["text"]
y_train = train_df["category"]

X_test = test_df["text"]
y_test = test_df["category"]

print("Train shape:", train_df.shape)
print("Test shape:", test_df.shape)

Train shape: (10003, 2)
Test shape: (3080, 2)

Step 4 — Create TF-IDF

In [5]:
tfidf = TfidfVectorizer(
    lowercase=True,
    max_features=20000,
    ngram_range=(1, 2)
)

print("TF-IDF vectorizer created")

TF-IDF vectorizer created

In [7]:
print("Training TF-IDF shape:", X_train_tfidf.shape)
print("Test TF-IDF shape:", X_test_tfidf.shape)

Training TF-IDF shape: (10003, 20000)
Test TF-IDF shape: (3080, 20000)

In [8]:
model = LogisticRegression(
    max_iter=1000
)

model.fit(X_train_tfidf, y_train)

print("Model training completed!")

Model training completed!

Make predictions

In [9]:
y_pred = model.predict(X_test_tfidf)

print("Prediction completed!")
print("Number of predictions:", len(y_pred))

Prediction completed!
Number of predictions: 3080

Calculate Precision, Recall , F1 and Accuracy

In [10]:
precision = precision_score(
    y_test,
    y_pred,
    average="weighted"
)

recall = recall_score(
    y_test,
    y_pred,
    average="weighted"
)

f1 = f1_score(
    y_test,
    y_pred,
    average="weighted"
)
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)
print("Accuracy (%):", accuracy * 100)

print("Precision:", precision)
print("Recall   :", recall)
print("F1 Score :", f1)
print(classification_report(y_test, y_pred))

Accuracy: 0.8568181818181818
Accuracy (%): 85.68181818181819
Precision: 0.8670838461790208
Recall   : 0.8568181818181818
F1 Score : 0.8553668264645073
                                                  precision    recall  f1-score   support

                           Refund_not_showing_up       0.84      0.95      0.89        40
                                activate_my_card       1.00      0.93      0.96        40
                                       age_limit       1.00      1.00      1.00        40
                         apple_pay_or_google_pay       0.98      1.00      0.99        40
                                     atm_support       0.86      0.80      0.83        40
                                automatic_top_up       1.00      0.90      0.95        40
         balance_not_updated_after_bank_transfer       0.65      0.80      0.72        40
balance_not_updated_after_cheque_or_cash_deposit       0.84      0.93      0.88        40
                         beneficiary_not_allowed       0.90      0.88      0.89        40
                                 cancel_transfer       0.88      0.95      0.92        40
                            card_about_to_expire       0.91      1.00      0.95        40
                                 card_acceptance       0.88      0.70      0.78        40
                                    card_arrival       0.72      0.82      0.77        40
                          card_delivery_estimate       0.90      0.88      0.89        40
                                    card_linking       0.91      0.97      0.94        40
                                card_not_working       0.59      0.82      0.69        40
                        card_payment_fee_charged       0.85      0.85      0.85        40
                     card_payment_not_recognised       0.76      0.70      0.73        40
                card_payment_wrong_exchange_rate       0.88      0.95      0.92        40
                                  card_swallowed       1.00      0.75      0.86        40
                          cash_withdrawal_charge       0.86      0.90      0.88        40
                  cash_withdrawal_not_recognised       0.80      0.80      0.80        40
                                      change_pin       1.00      0.93      0.96        40
                                compromised_card       0.82      0.70      0.76        40
                         contactless_not_working       1.00      0.72      0.84        40
                                 country_support       0.90      0.90      0.90        40
                           declined_card_payment       0.70      0.97      0.81        40
                        declined_cash_withdrawal       0.77      0.93      0.84        40
                               declined_transfer       1.00      0.85      0.92        40
             direct_debit_payment_not_recognised       0.97      0.82      0.89        40
                          disposable_card_limits       0.80      0.82      0.81        40
                           edit_personal_details       0.98      1.00      0.99        40
                                 exchange_charge       0.85      0.85      0.85        40
                                   exchange_rate       0.90      0.93      0.91        40
                                exchange_via_app       0.83      0.85      0.84        40
                       extra_charge_on_statement       0.71      0.85      0.77        40
                                 failed_transfer       0.73      0.90      0.81        40
                           fiat_currency_support       0.89      0.78      0.83        40
                     get_disposable_virtual_card       0.71      0.75      0.73        40
                               get_physical_card       0.87      0.97      0.92        40
                              getting_spare_card       0.90      0.90      0.90        40
                            getting_virtual_card       0.64      0.95      0.77        40
                             lost_or_stolen_card       0.92      0.82      0.87        40
                            lost_or_stolen_phone       1.00      0.97      0.99        40
                             order_physical_card       0.84      0.80      0.82        40
                              passcode_forgotten       1.00      1.00      1.00        40
                            pending_card_payment       0.78      0.90      0.84        40
                         pending_cash_withdrawal       0.97      0.90      0.94        40
                                  pending_top_up       0.91      0.78      0.84        40
                                pending_transfer       0.83      0.60      0.70        40
                                     pin_blocked       0.97      0.82      0.89        40
                                 receiving_money       0.95      0.90      0.92        40
                                  request_refund       0.86      0.75      0.80        40
                          reverted_card_payment?       0.83      0.88      0.85        40
                  supported_cards_and_currencies       0.78      0.97      0.87        40
                               terminate_account       0.85      1.00      0.92        40
                  top_up_by_bank_transfer_charge       0.91      0.72      0.81        40
                           top_up_by_card_charge       0.93      0.95      0.94        40
                        top_up_by_cash_or_cheque       0.94      0.78      0.85        40
                                   top_up_failed       0.74      0.72      0.73        40
                                   top_up_limits       0.84      0.95      0.89        40
                                 top_up_reverted       0.82      0.82      0.82        40
                              topping_up_by_card       0.85      0.70      0.77        40
                       transaction_charged_twice       0.91      1.00      0.95        40
                            transfer_fee_charged       0.89      0.85      0.87        40
                           transfer_into_account       0.82      0.82      0.82        40
              transfer_not_received_by_recipient       0.76      0.85      0.80        40
                                 transfer_timing       0.77      0.85      0.81        40
                       unable_to_verify_identity       0.86      0.80      0.83        40
                              verify_my_identity       0.73      0.82      0.78        40
                          verify_source_of_funds       0.89      1.00      0.94        40
                                   verify_top_up       1.00      1.00      1.00        40
                        virtual_card_not_working       1.00      0.30      0.46        40
                              visa_or_mastercard       1.00      0.90      0.95        40
                             why_verify_identity       0.86      0.80      0.83        40
                   wrong_amount_of_cash_received       0.88      0.90      0.89        40
         wrong_exchange_rate_for_cash_withdrawal       0.87      0.68      0.76        40

                                        accuracy                           0.86      3080
                                       macro avg       0.87      0.86      0.86      3080
                                    weighted avg       0.87      0.86      0.86      3080

85.68% accuracy  - Classification_report

In [11]:
import joblib

joblib.dump(tfidf, "../models/tfidf_vectorizer.pkl")
joblib.dump(model, "../models/logistic_regression_model.pkl")

print("TF-IDF vectorizer saved!")
print("Logistic Regression model saved!")

TF-IDF vectorizer saved!
Logistic Regression model saved!

In [25]:
import joblib
import pandas as pd
from sklearn.metrics import classification_report

# Load model and vectorizer
model = joblib.load(
    r"C:\Users\GOPINATH\ALML\Models\logistic_regression_model.pkl"
)

vectorizer = joblib.load(
    r"C:\Users\GOPINATH\ALML\Models\tfidf_vectorizer.pkl"
)

# Prepare test data
y_test = test_df["category"]
X_test_tfidf = vectorizer.transform(test_df["text"])

# Predict
y_pred = model.predict(X_test_tfidf)

# Classification report
print(classification_report(y_test, y_pred))

# DataFrame version
report = classification_report(
    y_test,
    y_pred,
    output_dict=True
)

report_df = pd.DataFrame(report).transpose()

display(report_df)

                                                  precision    recall  f1-score   support

                           Refund_not_showing_up       0.84      0.95      0.89        40
                                activate_my_card       1.00      0.93      0.96        40
                                       age_limit       1.00      1.00      1.00        40
                         apple_pay_or_google_pay       0.98      1.00      0.99        40
                                     atm_support       0.86      0.80      0.83        40
                                automatic_top_up       1.00      0.90      0.95        40
         balance_not_updated_after_bank_transfer       0.65      0.80      0.72        40
balance_not_updated_after_cheque_or_cash_deposit       0.84      0.93      0.88        40
                         beneficiary_not_allowed       0.90      0.88      0.89        40
                                 cancel_transfer       0.88      0.95      0.92        40
                            card_about_to_expire       0.91      1.00      0.95        40
                                 card_acceptance       0.88      0.70      0.78        40
                                    card_arrival       0.72      0.82      0.77        40
                          card_delivery_estimate       0.90      0.88      0.89        40
                                    card_linking       0.91      0.97      0.94        40
                                card_not_working       0.59      0.82      0.69        40
                        card_payment_fee_charged       0.85      0.85      0.85        40
                     card_payment_not_recognised       0.76      0.70      0.73        40
                card_payment_wrong_exchange_rate       0.88      0.95      0.92        40
                                  card_swallowed       1.00      0.75      0.86        40
                          cash_withdrawal_charge       0.86      0.90      0.88        40
                  cash_withdrawal_not_recognised       0.80      0.80      0.80        40
                                      change_pin       1.00      0.93      0.96        40
                                compromised_card       0.82      0.70      0.76        40
                         contactless_not_working       1.00      0.72      0.84        40
                                 country_support       0.90      0.90      0.90        40
                           declined_card_payment       0.70      0.97      0.81        40
                        declined_cash_withdrawal       0.77      0.93      0.84        40
                               declined_transfer       1.00      0.85      0.92        40
             direct_debit_payment_not_recognised       0.97      0.82      0.89        40
                          disposable_card_limits       0.80      0.82      0.81        40
                           edit_personal_details       0.98      1.00      0.99        40
                                 exchange_charge       0.85      0.85      0.85        40
                                   exchange_rate       0.90      0.93      0.91        40
                                exchange_via_app       0.83      0.85      0.84        40
                       extra_charge_on_statement       0.71      0.85      0.77        40
                                 failed_transfer       0.73      0.90      0.81        40
                           fiat_currency_support       0.89      0.78      0.83        40
                     get_disposable_virtual_card       0.71      0.75      0.73        40
                               get_physical_card       0.87      0.97      0.92        40
                              getting_spare_card       0.90      0.90      0.90        40
                            getting_virtual_card       0.64      0.95      0.77        40
                             lost_or_stolen_card       0.92      0.82      0.87        40
                            lost_or_stolen_phone       1.00      0.97      0.99        40
                             order_physical_card       0.84      0.80      0.82        40
                              passcode_forgotten       1.00      1.00      1.00        40
                            pending_card_payment       0.78      0.90      0.84        40
                         pending_cash_withdrawal       0.97      0.90      0.94        40
                                  pending_top_up       0.91      0.78      0.84        40
                                pending_transfer       0.83      0.60      0.70        40
                                     pin_blocked       0.97      0.82      0.89        40
                                 receiving_money       0.95      0.90      0.92        40
                                  request_refund       0.86      0.75      0.80        40
                          reverted_card_payment?       0.83      0.88      0.85        40
                  supported_cards_and_currencies       0.78      0.97      0.87        40
                               terminate_account       0.85      1.00      0.92        40
                  top_up_by_bank_transfer_charge       0.91      0.72      0.81        40
                           top_up_by_card_charge       0.93      0.95      0.94        40
                        top_up_by_cash_or_cheque       0.94      0.78      0.85        40
                                   top_up_failed       0.74      0.72      0.73        40
                                   top_up_limits       0.84      0.95      0.89        40
                                 top_up_reverted       0.82      0.82      0.82        40
                              topping_up_by_card       0.85      0.70      0.77        40
                       transaction_charged_twice       0.91      1.00      0.95        40
                            transfer_fee_charged       0.89      0.85      0.87        40
                           transfer_into_account       0.82      0.82      0.82        40
              transfer_not_received_by_recipient       0.76      0.85      0.80        40
                                 transfer_timing       0.77      0.85      0.81        40
                       unable_to_verify_identity       0.86      0.80      0.83        40
                              verify_my_identity       0.73      0.82      0.78        40
                          verify_source_of_funds       0.89      1.00      0.94        40
                                   verify_top_up       1.00      1.00      1.00        40
                        virtual_card_not_working       1.00      0.30      0.46        40
                              visa_or_mastercard       1.00      0.90      0.95        40
                             why_verify_identity       0.86      0.80      0.83        40
                   wrong_amount_of_cash_received       0.88      0.90      0.89        40
         wrong_exchange_rate_for_cash_withdrawal       0.87      0.68      0.76        40

                                        accuracy                           0.86      3080
                                       macro avg       0.87      0.86      0.86      3080
                                    weighted avg       0.87      0.86      0.86      3080

,precision,recall,f1-score,support
Refund_not_showing_up,0.844444,0.950000,0.894118,40.000000
activate_my_card,1.000000,0.925000,0.961039,40.000000
age_limit,1.000000,1.000000,1.000000,40.000000
apple_pay_or_google_pay,0.975610,1.000000,0.987654,40.000000
atm_support,0.864865,0.800000,0.831169,40.000000
...,...,...,...,...
wrong_amount_of_cash_received,0.878049,0.900000,0.888889,40.000000
wrong_exchange_rate_for_cash_withdrawal,0.870968,0.675000,0.760563,40.000000
accuracy,0.856818,0.856818,0.856818,0.856818
macro avg,0.867084,0.856818,0.855367,3080.000000
weighted avg,0.867084,0.856818,0.855367,3080.000000

In [2]:
import pandas as pd
import joblib

# Load datasets
train_df = pd.read_csv(
    r"C:\Users\GOPINATH\ALML\data\train.csv"
)

test_df = pd.read_csv(
    r"C:\Users\GOPINATH\ALML\data\test.csv"
)

# Load the SAME TF-IDF vectorizer from Day 2
vectorizer = joblib.load(
    r"C:\Users\GOPINATH\ALML\Models\tfidf_vectorizer.pkl"
)

# Prepare labels
y_train = train_df["category"]
y_test = test_df["category"]

# Transform text using the saved vectorizer
X_train_tfidf = vectorizer.transform(train_df["text"])
X_test_tfidf = vectorizer.transform(test_df["text"])

print("Training TF-IDF:", X_train_tfidf.shape)
print("Test TF-IDF:", X_test_tfidf.shape)
print("Training labels:", len(y_train))
print("Test labels:", len(y_test))

Training TF-IDF: (10003, 20000)
Test TF-IDF: (3080, 20000)
Training labels: 10003
Test labels: 3080

In [3]:
from sklearn.svm import LinearSVC

svm_model = LinearSVC(
    C=1.0,
    max_iter=1000,
    dual="auto"
)

svm_model.fit(X_train_tfidf, y_train)

print("Linear SVM training completed!")

Linear SVM training completed!

Day 3 — Step 3: SVM Predictions

In [4]:
y_pred_svm = svm_model.predict(X_test_tfidf)

print("Number of SVM predictions:", len(y_pred_svm))

Number of SVM predictions: 3080

Step 4: Calculate SVM metrics

In [5]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

svm_accuracy = accuracy_score(y_test, y_pred_svm)

svm_precision = precision_score(
    y_test,
    y_pred_svm,
    average="weighted"
)

svm_recall = recall_score(
    y_test,
    y_pred_svm,
    average="weighted"
)

svm_f1 = f1_score(
    y_test,
    y_pred_svm,
    average="weighted"
)

print("SVM Accuracy :", svm_accuracy)
print("SVM Accuracy (%):", svm_accuracy * 100)
print("SVM Precision:", svm_precision)
print("SVM Recall   :", svm_recall)
print("SVM F1 Score :", svm_f1)

SVM Accuracy : 0.8931818181818182
SVM Accuracy (%): 89.31818181818181
SVM Precision: 0.8972269238712747
SVM Recall   : 0.8931818181818182
SVM F1 Score : 0.8932897238176926

classification report

In [6]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_svm))

                                                  precision    recall  f1-score   support

                           Refund_not_showing_up       0.95      0.95      0.95        40
                                activate_my_card       0.97      0.95      0.96        40
                                       age_limit       0.98      1.00      0.99        40
                         apple_pay_or_google_pay       1.00      1.00      1.00        40
                                     atm_support       0.93      0.93      0.93        40
                                automatic_top_up       1.00      0.97      0.99        40
         balance_not_updated_after_bank_transfer       0.69      0.78      0.73        40
balance_not_updated_after_cheque_or_cash_deposit       0.88      0.93      0.90        40
                         beneficiary_not_allowed       0.95      0.95      0.95        40
                                 cancel_transfer       0.95      0.95      0.95        40
                            card_about_to_expire       0.95      0.97      0.96        40
                                 card_acceptance       0.92      0.85      0.88        40
                                    card_arrival       0.83      0.85      0.84        40
                          card_delivery_estimate       0.85      0.88      0.86        40
                                    card_linking       0.95      0.97      0.96        40
                                card_not_working       0.71      0.85      0.77        40
                        card_payment_fee_charged       0.95      0.88      0.91        40
                     card_payment_not_recognised       0.94      0.75      0.83        40
                card_payment_wrong_exchange_rate       0.88      0.90      0.89        40
                                  card_swallowed       1.00      0.88      0.93        40
                          cash_withdrawal_charge       1.00      0.93      0.96        40
                  cash_withdrawal_not_recognised       0.86      0.95      0.90        40
                                      change_pin       1.00      0.95      0.97        40
                                compromised_card       0.88      0.90      0.89        40
                         contactless_not_working       1.00      0.90      0.95        40
                                 country_support       0.87      0.97      0.92        40
                           declined_card_payment       0.77      0.93      0.84        40
                        declined_cash_withdrawal       0.90      0.90      0.90        40
                               declined_transfer       0.97      0.82      0.89        40
             direct_debit_payment_not_recognised       0.85      0.88      0.86        40
                          disposable_card_limits       0.94      0.85      0.89        40
                           edit_personal_details       0.98      1.00      0.99        40
                                 exchange_charge       0.92      0.88      0.90        40
                                   exchange_rate       0.88      0.95      0.92        40
                                exchange_via_app       0.88      0.93      0.90        40
                       extra_charge_on_statement       0.81      0.85      0.83        40
                                 failed_transfer       0.74      0.85      0.79        40
                           fiat_currency_support       0.97      0.78      0.86        40
                     get_disposable_virtual_card       0.92      0.88      0.90        40
                               get_physical_card       0.84      0.93      0.88        40
                              getting_spare_card       0.93      0.93      0.93        40
                            getting_virtual_card       0.78      0.95      0.85        40
                             lost_or_stolen_card       0.82      0.90      0.86        40
                            lost_or_stolen_phone       1.00      0.97      0.99        40
                             order_physical_card       0.89      0.82      0.86        40
                              passcode_forgotten       1.00      1.00      1.00        40
                            pending_card_payment       0.82      0.90      0.86        40
                         pending_cash_withdrawal       0.92      0.88      0.90        40
                                  pending_top_up       0.91      0.80      0.85        40
                                pending_transfer       0.79      0.68      0.73        40
                                     pin_blocked       0.89      0.82      0.86        40
                                 receiving_money       1.00      0.97      0.99        40
                                  request_refund       0.95      0.90      0.92        40
                          reverted_card_payment?       0.86      0.95      0.90        40
                  supported_cards_and_currencies       0.77      1.00      0.87        40
                               terminate_account       0.98      1.00      0.99        40
                  top_up_by_bank_transfer_charge       0.89      0.85      0.87        40
                           top_up_by_card_charge       0.93      0.95      0.94        40
                        top_up_by_cash_or_cheque       0.89      0.82      0.86        40
                                   top_up_failed       0.76      0.78      0.77        40
                                   top_up_limits       0.89      0.97      0.93        40
                                 top_up_reverted       0.82      0.82      0.82        40
                              topping_up_by_card       0.89      0.80      0.84        40
                       transaction_charged_twice       0.91      1.00      0.95        40
                            transfer_fee_charged       0.88      0.88      0.88        40
                           transfer_into_account       0.88      0.90      0.89        40
              transfer_not_received_by_recipient       0.76      0.78      0.77        40
                                 transfer_timing       0.91      0.80      0.85        40
                       unable_to_verify_identity       0.82      0.82      0.82        40
                              verify_my_identity       0.79      0.75      0.77        40
                          verify_source_of_funds       0.93      1.00      0.96        40
                                   verify_top_up       0.98      1.00      0.99        40
                        virtual_card_not_working       1.00      0.80      0.89        40
                              visa_or_mastercard       1.00      0.93      0.96        40
                             why_verify_identity       0.87      0.85      0.86        40
                   wrong_amount_of_cash_received       0.90      0.90      0.90        40
         wrong_exchange_rate_for_cash_withdrawal       0.83      0.72      0.77        40

                                        accuracy                           0.89      3080
                                       macro avg       0.90      0.89      0.89      3080
                                    weighted avg       0.90      0.89      0.89      3080

Step 1 — Find incorrect predictions

In [7]:
import pandas as pd

error_df = test_df.copy()

error_df["predicted_category"] = y_pred_svm

# Keep only incorrect predictions
errors = error_df[
    error_df["category"] != error_df["predicted_category"]
].copy()

print("Total test samples:", len(test_df))
print("Incorrect predictions:", len(errors))
print("Correct predictions:", len(test_df) - len(errors))

Total test samples: 3080
Incorrect predictions: 329
Correct predictions: 2751

In [8]:
errors[["text", "category", "predicted_category"]].head(20)

,text,category,predicted_category
0,How do I locate my card?,card_arrival,get_physical_card
2,I ordered a card but it has not arrived. Help ...,card_arrival,transfer_not_received_by_recipient
4,My card has not arrived yet.,card_arrival,transfer_not_received_by_recipient
5,When will I get my card?,card_arrival,card_delivery_estimate
11,How long does a card delivery take?,card_arrival,card_delivery_estimate
36,I'm starting to think my card is lost because ...,card_arrival,lost_or_stolen_card
79,Can I link another card to my account?,card_linking,getting_spare_card
93,Is it a good time to exchange?,exchange_rate,exchange_charge
106,The exchange rate would be?,exchange_rate,wrong_exchange_rate_for_cash_withdrawal
123,The exchange rate was wrong when I bought some...,card_payment_wrong_exchange_rate,wrong_exchange_rate_for_cash_withdrawal
138,Why am I being charged more ?,card_payment_wrong_exchange_rate,card_payment_fee_charged
145,The exchange rate seems off on this transaction,card_payment_wrong_exchange_rate,wrong_exchange_rate_for_cash_withdrawal
156,How can I check the exchange rate applied to m...,card_payment_wrong_exchange_rate,wrong_exchange_rate_for_cash_withdrawal
164,There is a fee I don't recognize on my statement.,extra_charge_on_statement,card_payment_not_recognised
166,Can you explain what this random $1 charge is?,extra_charge_on_statement,direct_debit_payment_not_recognised
172,When will the $1 transaction be credited to me?,extra_charge_on_statement,transfer_not_received_by_recipient
173,Where did this fee come from?,extra_charge_on_statement,transfer_fee_charged
196,"It's been two weeks, why has the transaction f...",extra_charge_on_statement,reverted_card_payment?
197,What is the €1 fee for?,extra_charge_on_statement,top_up_by_bank_transfer_charge
222,I made a withdrawal from my account but it has...,pending_cash_withdrawal,cash_withdrawal_not_recognised

In [9]:
confusion_pairs = (
    errors.groupby(["category", "predicted_category"])
    .size()
    .reset_index(name="count")
    .sort_values("count", ascending=False)
)

confusion_pairs.head(20)

,category,predicted_category,count
214,virtual_card_not_working,getting_virtual_card,5
206,unable_to_verify_identity,verify_my_identity,5
10,balance_not_updated_after_bank_transfer,transfer_not_received_by_recipient,4
143,pending_transfer,balance_not_updated_after_bank_transfer,4
209,verify_my_identity,unable_to_verify_identity,4
223,wrong_exchange_rate_for_cash_withdrawal,card_payment_wrong_exchange_rate,4
176,top_up_reverted,top_up_failed,4
211,verify_my_identity,why_verify_identity,4
144,pending_transfer,failed_transfer,4
107,fiat_currency_support,exchange_via_app,3
172,top_up_failed,top_up_reverted,3
150,pin_blocked,get_physical_card,3
85,exchange_charge,exchange_rate,3
149,pin_blocked,card_not_working,3
141,pending_top_up,top_up_failed,3
142,pending_top_up,top_up_reverted,3
108,fiat_currency_support,supported_cards_and_currencies,3
217,why_verify_identity,unable_to_verify_identity,3
193,transfer_not_received_by_recipient,balance_not_updated_after_bank_transfer,3
166,top_up_by_cash_or_cheque,supported_cards_and_currencies,3

TF-IDF tuning + Linear SVM.

Step 4 — Create tuned TF-IDF

In [10]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_tuned = TfidfVectorizer(
    max_features=30000,
    ngram_range=(1, 2),
    min_df=2,
    sublinear_tf=True
)

X_train_tuned = tfidf_tuned.fit_transform(train_df["text"])
X_test_tuned = tfidf_tuned.transform(test_df["text"])

print("Tuned Training TF-IDF shape:", X_train_tuned.shape)
print("Tuned Test TF-IDF shape:", X_test_tuned.shape)

Tuned Training TF-IDF shape: (10003, 10292)
Tuned Test TF-IDF shape: (3080, 10292)

Step 5 — Train the tuned Linear SVM

In [11]:
from sklearn.svm import LinearSVC

svm_tuned = LinearSVC(
    C=1.0,
    max_iter=1000,
    dual="auto"
)

svm_tuned.fit(X_train_tuned, y_train)

print("Tuned Linear SVM training completed!")

Tuned Linear SVM training completed!

In [12]:
y_pred_tuned = svm_tuned.predict(X_test_tuned)

print("Number of predictions:", len(y_pred_tuned))

Number of predictions: 3080

Step 6 — Evaluate the tuned SVM

In [13]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

tuned_accuracy = accuracy_score(y_test, y_pred_tuned)

tuned_precision = precision_score(
    y_test,
    y_pred_tuned,
    average="weighted"
)

tuned_recall = recall_score(
    y_test,
    y_pred_tuned,
    average="weighted"
)

tuned_f1 = f1_score(
    y_test,
    y_pred_tuned,
    average="weighted"
)

print("Tuned SVM Accuracy :", tuned_accuracy)
print("Tuned SVM Accuracy (%):", tuned_accuracy * 100)
print("Tuned SVM Precision:", tuned_precision)
print("Tuned SVM Recall   :", tuned_recall)
print("Tuned SVM F1 Score :", tuned_f1)

Tuned SVM Accuracy : 0.8905844155844156
Tuned SVM Accuracy (%): 89.05844155844156
Tuned SVM Precision: 0.8943070830261277
Tuned SVM Recall   : 0.8905844155844156
Tuned SVM F1 Score : 0.8905649267508707

Logistic Regression
        ↓
    85.68%

Linear SVM
        ↓
    89.32%  ← current best

Tuned TF-IDF + Linear SVM
        ↓
    89.06%

Naive Bayes

In [14]:
from sklearn.naive_bayes import MultinomialNB

nb_model = MultinomialNB()

nb_model.fit(X_train_tfidf, y_train)

print("Naive Bayes training completed!")

Naive Bayes training completed!

In [16]:
y_pred_nb = nb_model.predict(X_test_tfidf)

print("Number of Naive Bayes predictions:", len(y_pred_nb))

Number of Naive Bayes predictions: 3080

In [17]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

nb_accuracy = accuracy_score(y_test, y_pred_nb)

nb_precision = precision_score(
    y_test,
    y_pred_nb,
    average="weighted"
)

nb_recall = recall_score(
    y_test,
    y_pred_nb,
    average="weighted"
)

nb_f1 = f1_score(
    y_test,
    y_pred_nb,
    average="weighted"
)

print("Naive Bayes Accuracy :", nb_accuracy)
print("Naive Bayes Accuracy (%):", nb_accuracy * 100)
print("Naive Bayes Precision:", nb_precision)
print("Naive Bayes Recall   :", nb_recall)
print("Naive Bayes F1 Score :", nb_f1)

Naive Bayes Accuracy : 0.7974025974025974
Naive Bayes Accuracy (%): 79.74025974025975
Naive Bayes Precision: 0.8348981522376847
Naive Bayes Recall   : 0.7974025974025974
Naive Bayes F1 Score : 0.7832867505259421

Linear SVM: 89.32% → current highest measured accuracy
Tuned SVM: 89.06% → tuning didn't improve the original SVM
Logistic Regression: 85.68%
Naive Bayes: 79.74%

In [18]:
from sklearn.linear_model import SGDClassifier

sgd_model = SGDClassifier(
    loss="hinge",
    max_iter=1000,
    random_state=42
)

sgd_model.fit(X_train_tfidf, y_train)

print("SGD Classifier training completed!")

SGD Classifier training completed!

In [19]:
y_pred_sgd = sgd_model.predict(X_test_tfidf)

print("Number of SGD predictions:", len(y_pred_sgd))

Number of SGD predictions: 3080

In [20]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

sgd_accuracy = accuracy_score(y_test, y_pred_sgd)
sgd_precision = precision_score(y_test, y_pred_sgd, average="weighted")
sgd_recall = recall_score(y_test, y_pred_sgd, average="weighted")
sgd_f1 = f1_score(y_test, y_pred_sgd, average="weighted")

print("SGD Accuracy :", sgd_accuracy)
print("SGD Accuracy (%):", sgd_accuracy * 100)
print("SGD Precision:", sgd_precision)
print("SGD Recall   :", sgd_recall)
print("SGD F1 Score :", sgd_f1)

SGD Accuracy : 0.8853896103896104
SGD Accuracy (%): 88.53896103896103
SGD Precision: 0.8899007628095247
SGD Recall   : 0.8853896103896104
SGD F1 Score : 0.8849925966909962

| Model               |   Accuracy | Precision |  Recall | F1 Score |
| ------------------- | ---------: | --------: | ------: | -------: |
| Logistic Regression |     85.68% |    86.71% |  85.68% |   85.54% |
| **Linear SVM**      | **89.32%** |   ~90.00% | ~89.00% |  ~89.00% |
| Tuned TF-IDF + SVM  |     89.06% |    89.43% |  89.06% |   89.06% |
| Naive Bayes         |     79.74% |    83.49% |  79.74% |   78.33% |
| SGD Classifier      |     88.54% |    88.99% |  88.54% |   88.50% |

Linear SVM: 89.32% — highest measured accuracy among these models.
Tuned TF-IDF + SVM: 89.06% — slightly lower than the original SVM.
SGD: 88.54% — good, but below SVM.
Logistic Regression: 85.68%.
Naive Bayes: 79.74%.

save the Linear SVM model and its original TF-IDF vectorizer because these are the pair that produced the 89.32% result

In [21]:
import joblib
import os

model_path = r"C:\Users\GOPINATH\ALML\Models\linear_svm_model.pkl"
vectorizer_path = r"C:\Users\GOPINATH\ALML\Models\tfidf_vectorizer.pkl"

joblib.dump(svm_model, model_path)

print("SVM model saved successfully!")
print("Model path:", model_path)
print("Vectorizer already saved at:", vectorizer_path)

SVM model saved successfully!
Model path: C:\Users\GOPINATH\ALML\Models\linear_svm_model.pkl
Vectorizer already saved at: C:\Users\GOPINATH\ALML\Models\tfidf_vectorizer.pkl

In [23]:
def predict_category(text):
    text_tfidf = vectorizer.transform([text])
    prediction = svm_model.predict(text_tfidf)
    return prediction[0]

In [24]:
text = "How do I locate my card?"

result = predict_category(text)

print("Input:", text)
print("Predicted category:", result)

Input: How do I locate my card?
Predicted category: get_physical_card

In [25]:
test_sentences = [
    "How do I locate my card?",
    "Where is my physical card?",
    "How long will my card take to arrive?",
    "I want to get a physical card",
    "My card has not arrived yet",
    "My card is not working"
]

for text in test_sentences:
    prediction = predict_category(text)
    print("Input:", text)
    print("Predicted:", prediction)
    print("-" * 60)

Input: How do I locate my card?
Predicted: get_physical_card
------------------------------------------------------------
Input: Where is my physical card?
Predicted: order_physical_card
------------------------------------------------------------
Input: How long will my card take to arrive?
Predicted: card_delivery_estimate
------------------------------------------------------------
Input: I want to get a physical card
Predicted: order_physical_card
------------------------------------------------------------
Input: My card has not arrived yet
Predicted: transfer_not_received_by_recipient
------------------------------------------------------------
Input: My card is not working
Predicted: card_not_working
------------------------------------------------------------

In [26]:
card_arrival_errors = errors[
    errors["category"] == "card_arrival"
]

print("Total card_arrival test samples:",
      (test_df["category"] == "card_arrival").sum())

print("Incorrect card_arrival predictions:",
      len(card_arrival_errors))

print("\nPredicted categories:")
print(card_arrival_errors["predicted_category"].value_counts())

Total card_arrival test samples: 40
Incorrect card_arrival predictions: 6

Predicted categories:
predicted_category
transfer_not_received_by_recipient    2
card_delivery_estimate                2
get_physical_card                     1
lost_or_stolen_card                   1
Name: count, dtype: int64

In [27]:
confusion_pairs = (
    errors.groupby(["category", "predicted_category"])
    .size()
    .reset_index(name="count")
    .sort_values("count", ascending=False)
)

print(confusion_pairs.head(20).to_string(index=False))

                               category                      predicted_category  count
               virtual_card_not_working                    getting_virtual_card      5
              unable_to_verify_identity                      verify_my_identity      5
balance_not_updated_after_bank_transfer      transfer_not_received_by_recipient      4
                       pending_transfer balance_not_updated_after_bank_transfer      4
                     verify_my_identity               unable_to_verify_identity      4
wrong_exchange_rate_for_cash_withdrawal        card_payment_wrong_exchange_rate      4
                        top_up_reverted                           top_up_failed      4
                     verify_my_identity                     why_verify_identity      4
                       pending_transfer                         failed_transfer      4
                  fiat_currency_support                        exchange_via_app      3
                          top_up_failed                         top_up_reverted      3
                            pin_blocked                       get_physical_card      3
                        exchange_charge                           exchange_rate      3
                            pin_blocked                        card_not_working      3
                         pending_top_up                           top_up_failed      3
                         pending_top_up                         top_up_reverted      3
                  fiat_currency_support          supported_cards_and_currencies      3
                    why_verify_identity               unable_to_verify_identity      3
     transfer_not_received_by_recipient balance_not_updated_after_bank_transfer      3
               top_up_by_cash_or_cheque          supported_cards_and_currencies      3

In [28]:
from sklearn.svm import LinearSVC

svm_balanced = LinearSVC(
    C=1.0,
    class_weight="balanced",
    max_iter=1000,
    dual="auto"
)

svm_balanced.fit(X_train_tfidf, y_train)

print("Balanced SVM training completed!")

Balanced SVM training completed!

In [30]:
y_pred_balanced = svm_balanced.predict(X_test_tfidf)

print("Number of predictions:", len(y_pred_balanced))

Number of predictions: 3080

In [31]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

balanced_accuracy = accuracy_score(y_test, y_pred_balanced)
balanced_precision = precision_score(
    y_test, y_pred_balanced, average="weighted"
)
balanced_recall = recall_score(
    y_test, y_pred_balanced, average="weighted"
)
balanced_f1 = f1_score(
    y_test, y_pred_balanced, average="weighted"
)

print("Balanced SVM Accuracy :", balanced_accuracy)
print("Balanced SVM Accuracy (%):", balanced_accuracy * 100)
print("Balanced SVM Precision:", balanced_precision)
print("Balanced SVM Recall   :", balanced_recall)
print("Balanced SVM F1 Score :", balanced_f1)

Balanced SVM Accuracy : 0.8964285714285715
Balanced SVM Accuracy (%): 89.64285714285715
Balanced SVM Precision: 0.8998218116951351
Balanced SVM Recall   : 0.8964285714285715
Balanced SVM F1 Score : 0.8964325051152551

In [ ]:
Model	Accuracy	Precision	Recall	F1 Score
Logistic Regression	85.68%	86.71%	85.68%	85.54%
Linear SVM	89.32%	~90.00%	~89.00%	~89.00%
Tuned TF-IDF + SVM	89.06%	89.43%	89.06%	89.06%
Naive Bayes	79.74%	83.49%	79.74%	78.33%
SGD	88.54%	88.99%	88.54%	88.50%
Balanced Linear SVM	89.64%	89.98%	89.64%	89.64%

In [ ]:
TF-IDF
   ↓
Linear SVM
   ↓
class_weight="balanced"
   ↓
89.64% accuracy

In [32]:
import joblib

balanced_model_path = r"C:\Users\GOPINATH\ALML\Models\balanced_svm_model.pkl"

joblib.dump(svm_balanced, balanced_model_path)

print("Balanced SVM saved successfully!")
print("Model path:", balanced_model_path)

Balanced SVM saved successfully!
Model path: C:\Users\GOPINATH\ALML\Models\balanced_svm_model.pkl

In [33]:
from sklearn.metrics import classification_report

balanced_report = classification_report(
    y_test,
    y_pred_balanced
)

print("Classification Report - Balanced SVM")
print("=" * 70)
print(balanced_report)

Classification Report - Balanced SVM
======================================================================
                                                  precision    recall  f1-score   support

                           Refund_not_showing_up       0.95      0.95      0.95        40
                                activate_my_card       0.97      0.95      0.96        40
                                       age_limit       0.95      1.00      0.98        40
                         apple_pay_or_google_pay       1.00      1.00      1.00        40
                                     atm_support       0.93      0.93      0.93        40
                                automatic_top_up       1.00      0.97      0.99        40
         balance_not_updated_after_bank_transfer       0.69      0.78      0.73        40
balance_not_updated_after_cheque_or_cash_deposit       0.88      0.93      0.90        40
                         beneficiary_not_allowed       0.95      0.95      0.95        40
                                 cancel_transfer       0.95      0.95      0.95        40
                            card_about_to_expire       0.95      0.97      0.96        40
                                 card_acceptance       0.92      0.90      0.91        40
                                    card_arrival       0.89      0.82      0.86        40
                          card_delivery_estimate       0.83      0.88      0.85        40
                                    card_linking       0.95      0.97      0.96        40
                                card_not_working       0.72      0.85      0.78        40
                        card_payment_fee_charged       0.95      0.88      0.91        40
                     card_payment_not_recognised       0.94      0.78      0.85        40
                card_payment_wrong_exchange_rate       0.88      0.90      0.89        40
                                  card_swallowed       1.00      0.93      0.96        40
                          cash_withdrawal_charge       1.00      0.93      0.96        40
                  cash_withdrawal_not_recognised       0.86      0.95      0.90        40
                                      change_pin       1.00      0.95      0.97        40
                                compromised_card       0.84      0.90      0.87        40
                         contactless_not_working       1.00      0.95      0.97        40
                                 country_support       0.91      0.97      0.94        40
                           declined_card_payment       0.79      0.93      0.85        40
                        declined_cash_withdrawal       0.90      0.90      0.90        40
                               declined_transfer       0.97      0.82      0.89        40
             direct_debit_payment_not_recognised       0.90      0.88      0.89        40
                          disposable_card_limits       0.94      0.85      0.89        40
                           edit_personal_details       0.98      1.00      0.99        40
                                 exchange_charge       0.92      0.88      0.90        40
                                   exchange_rate       0.86      0.95      0.90        40
                                exchange_via_app       0.88      0.93      0.90        40
                       extra_charge_on_statement       0.81      0.88      0.84        40
                                 failed_transfer       0.74      0.85      0.79        40
                           fiat_currency_support       0.97      0.78      0.86        40
                     get_disposable_virtual_card       0.92      0.88      0.90        40
                               get_physical_card       0.84      0.93      0.88        40
                              getting_spare_card       0.93      0.93      0.93        40
                            getting_virtual_card       0.81      0.95      0.87        40
                             lost_or_stolen_card       0.80      0.90      0.85        40
                            lost_or_stolen_phone       1.00      0.97      0.99        40
                             order_physical_card       0.89      0.85      0.87        40
                              passcode_forgotten       1.00      1.00      1.00        40
                            pending_card_payment       0.84      0.90      0.87        40
                         pending_cash_withdrawal       0.97      0.90      0.94        40
                                  pending_top_up       0.89      0.78      0.83        40
                                pending_transfer       0.79      0.65      0.71        40
                                     pin_blocked       0.92      0.82      0.87        40
                                 receiving_money       1.00      0.97      0.99        40
                                  request_refund       0.97      0.90      0.94        40
                          reverted_card_payment?       0.86      0.95      0.90        40
                  supported_cards_and_currencies       0.78      1.00      0.88        40
                               terminate_account       0.95      1.00      0.98        40
                  top_up_by_bank_transfer_charge       0.89      0.85      0.87        40
                           top_up_by_card_charge       0.93      0.95      0.94        40
                        top_up_by_cash_or_cheque       0.92      0.85      0.88        40
                                   top_up_failed       0.78      0.78      0.78        40
                                   top_up_limits       0.89      0.97      0.93        40
                                 top_up_reverted       0.82      0.82      0.82        40
                              topping_up_by_card       0.86      0.80      0.83        40
                       transaction_charged_twice       0.91      1.00      0.95        40
                            transfer_fee_charged       0.88      0.88      0.88        40
                           transfer_into_account       0.88      0.90      0.89        40
              transfer_not_received_by_recipient       0.76      0.78      0.77        40
                                 transfer_timing       0.89      0.80      0.84        40
                       unable_to_verify_identity       0.82      0.82      0.82        40
                              verify_my_identity       0.79      0.75      0.77        40
                          verify_source_of_funds       0.93      1.00      0.96        40
                                   verify_top_up       0.98      1.00      0.99        40
                        virtual_card_not_working       1.00      0.85      0.92        40
                              visa_or_mastercard       1.00      0.93      0.96        40
                             why_verify_identity       0.87      0.85      0.86        40
                   wrong_amount_of_cash_received       0.92      0.90      0.91        40
         wrong_exchange_rate_for_cash_withdrawal       0.83      0.72      0.77        40

                                        accuracy                           0.90      3080
                                       macro avg       0.90      0.90      0.90      3080
                                    weighted avg       0.90      0.90      0.90      3080

Live Evaluation

In [9]:
test_queries = [
    "My card is not working",
    "How long will my card take to arrive?",
    "I forgot my password",
    "I want to get a physical card",
    "Why has my bank transfer not arrived?",
    "I cannot verify my identity",
    "My top up failed",
    "I want to exchange currency",
    "My virtual card is not working",
    "I lost my card"
]

for query in test_queries:
    prediction = predict_category(query)
    print("Query:", query)
    print("Prediction:", prediction)
    print("-" * 60)

Query: My card is not working
Prediction: card_not_working
------------------------------------------------------------
Query: How long will my card take to arrive?
Prediction: card_delivery_estimate
------------------------------------------------------------
Query: I forgot my password
Prediction: passcode_forgotten
------------------------------------------------------------
Query: I want to get a physical card
Prediction: order_physical_card
------------------------------------------------------------
Query: Why has my bank transfer not arrived?
Prediction: balance_not_updated_after_bank_transfer
------------------------------------------------------------
Query: I cannot verify my identity
Prediction: verify_my_identity
------------------------------------------------------------
Query: My top up failed
Prediction: top_up_failed
------------------------------------------------------------
Query: I want to exchange currency
Prediction: exchange_via_app
------------------------------------------------------------
Query: My virtual card is not working
Prediction: virtual_card_not_working
------------------------------------------------------------
Query: I lost my card
Prediction: lost_or_stolen_card
------------------------------------------------------------

                 Customer Query
                       ↓
                 Streamlit UI
                       ↓
                TF-IDF Vectorizer
                       ↓
                Balanced SVM
                       ↓
                Predicted Category

Streamlit